### ISSUE TITLE
图甚喜！借之😄

### ISSUE THREAD

**Issue by wangyingbo** [Leecason/Leecason#1]

**Comment by Leecason** [comment]
欢迎😄，我在这里找的 https://tenor.com/

**Comment by wangyingbo** [comment]
> 欢迎😄，我在这里找的 https://tenor.com/

嗯嗯，感谢！不过我发现githubusercontent图床被墙掉了，不开vpn好像访问不了，老哥有啥好用的图床吗？

**Comment by Leecason** [comment]
> > 欢迎😄，我在这里找的 https://tenor.com/
> 
> 嗯嗯，感谢！不过我发现githubusercontent图床被墙掉了，不开vpn好像访问不了，老哥有啥好用的图床吗？

https://zh-cn.imgbb.com/
